sudo: false
language: python
dist: xenial  # required for Python >= 3.7

python:
  - "3.7"

before_install:
  - pip install --quiet "pip>=19.0"
  - pip install --quiet tox coveralls

script:
  - tox -- --cov=wait_travis

after_success:
  # Strip off ".tox/..." from the coverage
  # (see also [[./tox.ini::coverage:paths]]):
  - .tox/py*/bin/coverage combine .coverage
  - coveralls

notifications:
  email: false
